name: Deploy
on:
  push: [ master ]

jobs:
  build:
    name: Run Web App
    runs-on: macos-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 12s
      - uses: rogeruiz22/demo-backend@master
        with:
          owner: roger uiz
          repo: demo-backend
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          worflow_file_name: master.yml
          ref: master
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
